name: "Hola Mundo"

on:
  push:
    branches: ["main"]

jobs:
  deploy-ActionsOne:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Hacemos pull del código

      - name: Correr migraciones
        run: echo "Correr migraciones"

      - name: Generar binario
        run: echo "Generar binario"

      - name: Publicar versión
        run: echo "Publicar version"
